apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: devops-deployment
spec:
  selector:
    matchLabels:
      app: ranjit-devops-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ranjit-devops-project
    spec:
      containers:
      - name: ranjit-devops-project
        image: ranjitkprajapati/simple-devops-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
