apiVersion: v1
kind: Service
metadata:
  name: devops-service
  labels:
    app: ranjit-devops-project
spec:
  selector:
    app: ranjit-devops-project
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
