---
- hosts: ansible-server
  #become: true

  tasks:

  - name: create docker image using war file
    command: docker build . -t simple-devops-image:latest
    args:
      chdir: /opt/kubernetes

  - name: create tag to image
    command: docker tag simple-devops-image ranjitkprajapati/simple-devops-image

  - name: push image on to dockerhub
    command: docker push ranjitkprajapati/simple-devops-image:latest

  - name: remove docker image from ansible server
    command: docker rmi simple-devops-image:latest ranjitkprajapati/simple-devops-image
    ignore_errors: yes
